### ISSUE TITLE
The Subtotal isn't Calculating Correctly

### ISSUE THREAD

**Issue by shaneliammurphy** [Boostly/fulfillment-client#2]
It should be listing 13.98

![image](https://user-images.githubusercontent.com/34665139/34216275-02f5c5c2-e565-11e7-9662-b63ea8e33301.png)

**Comment by shaneliammurphy** [comment]
We should also double check the taxes...

Since this is coming from God Mode, maybe these are Hardcoded numbers? Since we have that working correctly on the Order Client, if it's just duplicating what is in the order, then it should be okay.

**Comment by mikeyamadeo** [comment]
God mode numbers are hardcoded. I pushed new hardcoded #s anyways
